substitutions:
  name: ecodan-heatpump
  friendlyName: Ecodan heatpump
  uart_rx_pin: "17"
  uart_tx_pin: "16"

http_request:
  buffer_size_tx: 20248

ota:
  - platform: esphome
  - platform: http_request
  - platform: web_server

api:
  reboot_timeout: 0s

external_components:
  - source: github://gekkekoe/esphome-ecodan-hp@main
    components: [ ecodan, optimizer, asgard_dashboard ]
    refresh: always

packages:
  remote_package:
    url: https://github.com/gekkekoe/esphome-ecodan-hp/
    ref: main
    refresh: always
    files: [
            confs/base.yaml,
            confs/energy.yaml,
            confs/cpu-monitoring.yaml,
            confs/request-codes.yaml,
            confs/auto-adaptive.yaml,
            confs/esp32.yaml,
            confs/zone1.yaml,
            confs/server-control-z1.yaml,
            confs/ecodan-labels-en.yaml,
            confs/debug.yaml,
            confs/wifi.yaml,
           ]

logger:
  level: DEBUG
  baud_rate: 115200
  logs:
    ecodan.component: WARN
    auto_adaptive: DEBUG
    short_cycle: DEBUG

# Enable Web server.
web_server:
  port: 80
  local: true

ecodan:
  id: ecodan_instance
  uart_id: uart_ecodan

