substitutions:
  name: ecodan-heatpump
  friendlyName: Ecodan heatpump
  uart_rx_pin: "17"
  uart_tx_pin: "16"

http_request:
  buffer_size_tx: 20248

ota:
  - platform: esphome
  - platform: http_request
  - platform: web_server

api:
  reboot_timeout: 0s

external_components:
  - source:
      type: local
      path: components
    components: [ ecodan, optimizer, asgard_dashboard ]

packages:
  base: !include confs/base.yaml
  energy: !include confs/energy.yaml
  cpu: !include confs/cpu-monitoring.yaml
  requests: !include confs/request-codes.yaml
  adaptive: !include confs/auto-adaptive.yaml
  esp32: !include confs/esp32.yaml
  zone1: !include confs/zone1.yaml
  server: !include confs/server-control-z1.yaml
  labels: !include confs/ecodan-labels-en.yaml
  debug: !include confs/debug.yaml
  wifi: !include confs/wifi.yaml

logger:
  level: DEBUG
  baud_rate: 115200
  logs:
    ecodan.component: WARN
    auto_adaptive: DEBUG
    short_cycle: DEBUG

# Enable Web server.
web_server:
  port: 80
  local: true

ecodan:
  id: ecodan_instance
  uart_id: uart_ecodan

